import { Agent, AgentTemplate } from './types'

export const OFFICE_ROOMS = [
  { id: 'orchestration', name: 'Mission Control', color: '#9b6dff', x: 380, y: 40, w: 200, h: 100 },
  { id: 'client-services', name: 'Client Services', color: '#4f8ef7', x: 60, y: 180, w: 240, h: 170 },
  { id: 'creative', name: 'Creative Division', color: '#00d4aa', x: 350, y: 180, w: 260, h: 170 },
  { id: 'media', name: 'Media Division', color: '#ff5fa0', x: 660, y: 180, w: 220, h: 170 },
  { id: 'research', name: 'Research Division', color: '#38bdf8', x: 260, y: 390, w: 420, h: 110 },
]

export const AGENT_TEMPLATES: AgentTemplate[] = [
  {
    id: 'brand-strategist',
    name: 'Brand Strategist',
    role: 'Brand & Campaign Strategist',
    division: 'client-services',
    specialty: 'strategy',
    unit: 'client-services',
    color: '#9b6dff',
    accentColor: 'purple',
    avatar: 'bot-purple',
    bio: 'Leads brand strategy, campaign frameworks, and messaging architecture.',
    methodology: '',
    systemPrompt: `You are a Brand & Campaign Strategist. Turn client goals into sharp positioning, campaign direction, and executable strategy documents.`,
    provider: 'gemini',
    model: 'gemini-2.5-pro',
    temperature: 0.7,
    maxTokens: 1536,
    tools: ['web-search', 'analytics'],
    skills: ['brand strategy', 'campaign planning', 'messaging architecture'],
    responsibilities: ['Define positioning', 'Shape campaign strategy', 'Align messaging to business goals'],
    primaryOutputs: ['strategy-brief', 'campaign-strategy', 'client-brief'],
  },
  {
    id: 'traffic-manager',
    name: 'Traffic Manager',
    role: 'Project / Traffic Manager',
    division: 'client-services',
    specialty: 'project-management',
    unit: 'client-services',
    color: '#ffd166',
    accentColor: 'yellow',
    avatar: 'bot-yellow',
    bio: 'Keeps scopes, schedules, and handoffs on track.',
    methodology: '',
    systemPrompt: `You are a Project and Traffic Manager. Build timelines, organize dependencies, and keep delivery clean across the agency.`,
    provider: 'ollama',
    model: 'llama3.2:latest',
    temperature: 0.4,
    maxTokens: 1024,
    tools: ['document'],
    skills: ['scheduling', 'resource planning', 'delivery coordination'],
    responsibilities: ['Own timelines', 'Track dependencies', 'Flag blockers'],
    primaryOutputs: ['status-report', 'client-brief'],
  },
  {
    id: 'copywriter',
    name: 'Copy & Content Lead',
    role: 'Copy & Content Lead',
    division: 'creative',
    specialty: 'copy',
    unit: 'creative',
    color: '#ffd166',
    accentColor: 'yellow',
    avatar: 'bot-yellow',
    bio: 'Creates campaign copy, platform-native content, and editorial plans.',
    methodology: '',
    systemPrompt: `You are a Copy & Content Lead. Produce campaign copy, platform-native content, and content calendars with strong hooks and clear CTAs.`,
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    temperature: 0.8,
    maxTokens: 1280,
    tools: ['web-search', 'social'],
    skills: ['campaign copy', 'content calendars', 'social scripting'],
    responsibilities: ['Write campaign copy', 'Build content calendars', 'Adapt tone by channel'],
    primaryOutputs: ['campaign-copy', 'content-calendar'],
  },
  {
    id: 'visual-designer',
    name: 'Visual Production',
    role: 'Design & Visual Production Lead',
    division: 'creative',
    specialty: 'design',
    unit: 'creative',
    color: '#ff7c42',
    accentColor: 'orange',
    avatar: 'bot-orange',
    bio: 'Translates campaign ideas into visual output and creative asset systems.',
    methodology: '',
    systemPrompt: `You are a Design & Visual Production Lead. Create creative asset directions, image prompts, and production-ready visual concepts. When image generation is required, prepare prompts optimized for Nano Banana 2.`,
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    temperature: 0.75,
    maxTokens: 1024,
    tools: ['image-gen', 'document'],
    skills: ['art direction', 'visual systems', 'image prompting'],
    responsibilities: ['Create asset directions', 'Prepare Nano Banana 2 prompts', 'Package visual systems'],
    primaryOutputs: ['creative-asset'],
  },
]

export const DEFAULT_AGENTS: Agent[] = [
  // NOTE: All runtime agents (iris, sage, piper, maya, finn, echo, lyra, nova, dex, atlas)
  // are defined in config/agents/*.json and loaded via CONFIG_AGENTS in agents-from-config.ts.
  // Only additional/future agents that don't have config files should be added here.
  // The store uses ALL_DEFAULT_AGENTS = [IRIS_AGENT, ...DEFAULT_AGENTS].
]
