import { Agent, AgentTemplate } from './types'

export const OFFICE_ROOMS = [
  { id: 'orchestration', name: 'Mission Control', color: '#9b6dff', x: 380, y: 40, w: 200, h: 100 },
  { id: 'client-services', name: 'Client Services', color: '#4f8ef7', x: 60, y: 180, w: 240, h: 170 },
  { id: 'creative', name: 'Creative Division', color: '#00d4aa', x: 350, y: 180, w: 260, h: 170 },
  { id: 'media', name: 'Media Division', color: '#ff5fa0', x: 660, y: 180, w: 220, h: 170 },
  { id: 'research', name: 'Research Division', color: '#38bdf8', x: 260, y: 390, w: 420, h: 110 },
]

export const AGENT_TEMPLATES: AgentTemplate[] = [
  {
    id: 'brand-strategist',
    name: 'Brand Strategist',
    role: 'Brand & Campaign Strategist',
    division: 'client-services',
    specialty: 'strategy',
    unit: 'client-services',
    color: '#9b6dff',
    accentColor: 'purple',
    avatar: 'bot-purple',
    bio: 'Leads brand strategy, campaign frameworks, and messaging architecture.',
    methodology: '',
    systemPrompt: `You are a Brand & Campaign Strategist. Turn client goals into sharp positioning, campaign direction, and executable strategy documents.`,
    provider: 'gemini',
    model: 'gemini-2.5-pro',
    temperature: 0.7,
    maxTokens: 1536,
    tools: ['web-search', 'analytics'],
    skills: ['brand strategy', 'campaign planning', 'messaging architecture'],
    responsibilities: ['Define positioning', 'Shape campaign strategy', 'Align messaging to business goals'],
    primaryOutputs: ['strategy-brief', 'campaign-strategy', 'client-brief'],
  },
  {
    id: 'traffic-manager',
    name: 'Traffic Manager',
    role: 'Project / Traffic Manager',
    division: 'client-services',
    specialty: 'project-management',
    unit: 'client-services',
    color: '#ffd166',
    accentColor: 'yellow',
    avatar: 'bot-yellow',
    bio: 'Keeps scopes, schedules, and handoffs on track.',
    methodology: '',
    systemPrompt: `You are a Project and Traffic Manager. Build timelines, organize dependencies, and keep delivery clean across the agency.`,
    provider: 'ollama',
    model: 'llama3.2:latest',
    temperature: 0.4,
    maxTokens: 1024,
    tools: ['document'],
    skills: ['scheduling', 'resource planning', 'delivery coordination'],
    responsibilities: ['Own timelines', 'Track dependencies', 'Flag blockers'],
    primaryOutputs: ['status-report', 'client-brief'],
  },
  {
    id: 'copywriter',
    name: 'Copy & Content Lead',
    role: 'Copy & Content Lead',
    division: 'creative',
    specialty: 'copy',
    unit: 'creative',
    color: '#ffd166',
    accentColor: 'yellow',
    avatar: 'bot-yellow',
    bio: 'Creates campaign copy, platform-native content, and editorial plans.',
    methodology: '',
    systemPrompt: `You are a Copy & Content Lead. Produce campaign copy, platform-native content, and content calendars with strong hooks and clear CTAs.`,
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    temperature: 0.8,
    maxTokens: 1280,
    tools: ['web-search', 'social'],
    skills: ['campaign copy', 'content calendars', 'social scripting'],
    responsibilities: ['Write campaign copy', 'Build content calendars', 'Adapt tone by channel'],
    primaryOutputs: ['campaign-copy', 'content-calendar'],
  },
  {
    id: 'visual-designer',
    name: 'Visual Production',
    role: 'Design & Visual Production Lead',
    division: 'creative',
    specialty: 'design',
    unit: 'creative',
    color: '#ff7c42',
    accentColor: 'orange',
    avatar: 'bot-orange',
    bio: 'Translates campaign ideas into visual output and creative asset systems.',
    methodology: '',
    systemPrompt: `You are a Design & Visual Production Lead. Create creative asset directions, image prompts, and production-ready visual concepts. When image generation is required, prepare prompts optimized for Nano Banana 2.`,
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    temperature: 0.75,
    maxTokens: 1024,
    tools: ['image-gen', 'document'],
    skills: ['art direction', 'visual systems', 'image prompting'],
    responsibilities: ['Create asset directions', 'Prepare Nano Banana 2 prompts', 'Package visual systems'],
    primaryOutputs: ['creative-asset'],
  },
]

export const DEFAULT_AGENTS: Agent[] = [
  // ─── LYRA ─── Visual Production Lead
  {
    id: 'lyra',
    name: 'Lyra',
    role: 'Visual Production Lead',
    division: 'creative',
    specialty: 'design',
    unit: 'creative',
    color: '#00d4aa',
    accentColor: 'green',
    avatar: 'bot-green',
    systemPrompt: `You are Lyra, Visual Production Lead. You produce all visual assets from concept to final delivery, manage the asset library, ensure technical specs are met, adapt visuals across platforms, and maintain brand visual standards.`,
    provider: 'ollama',
    model: 'minimax-m2.7:cloud',
    temperature: 0.7,
    maxTokens: 1536,
    tools: ['web-search', 'figma', 'canva', 'image-gen', 'document'],
    skills: ['art-direction', 'visual-leadership', 'design-systems', 'visual-storytelling', 'cross-channel-adaptation', 'composition', 'color-theory', 'typography', 'creative-quality', 'creative-iteration', 'brand-consistency'],
    responsibilities: ['Produce all visual assets', 'Manage asset library and versioning', 'Ensure technical specs are met', 'Adapt visuals across platforms', 'Maintain brand visual standards'],
    primaryOutputs: ['creative-asset'],
    status: 'idle',
    currentTask: 'Preparing visual asset packs',
    lastActive: new Date().toISOString(),
    workload: 65,
    position: { x: 440, y: 260, room: 'creative' },
    bio: 'Produces all visual assets from concept to final delivery.',
    methodology: 'Visual Production Pipeline + Asset Management System',
  },

  // ─── PIPER ─── Project & Traffic Manager
  {
    id: 'piper',
    name: 'Piper',
    role: 'Project & Traffic Manager',
    division: 'orchestration',
    specialty: 'project-management',
    unit: 'orchestration',
    color: '#ffd166',
    accentColor: 'yellow',
    avatar: 'bot-yellow',
    systemPrompt: `You are Piper, Project & Traffic Manager. You keep projects on track, managing timelines, budgets, and creative workflow.`,
    provider: 'ollama',
    model: 'minimax-m2.7:cloud',
    temperature: 0.7,
    maxTokens: 1536,
    tools: ['web-search', 'document', 'spreadsheet', 'presentation'],
    skills: ['project-scheduling', 'traffic-coordination', 'resource-allocation', 'capacity-planning', 'scope-management', 'change-control', 'critical-path-analysis', 'deadline-management', 'workflow-optimization', 'agile-scrum', 'burndown-tracking', 'stakeholder-management', 'risk-assessment', 'timeline-planning'],
    responsibilities: ['Manage project timelines and deliverables', 'Coordinate creative traffic and workflow', 'Allocate resources across active projects', 'Track budget and scope changes', 'Report project status to leadership'],
    primaryOutputs: ['status-report', 'client-brief'],
    status: 'idle',
    currentTask: 'Tracking delivery schedule',
    lastActive: new Date().toISOString(),
    workload: 80,
    position: { x: 500, y: 70, room: 'orchestration' },
    bio: 'Keeps projects on track, managing timelines, budgets, and creative workflow.',
    methodology: 'Agile/Scrum + Waterfall + Critical Path Method',
  },

  // ─── SAGE ─── Client Services Director
  {
    id: 'sage',
    name: 'Sage',
    role: 'Client Services Director',
    division: 'client-services',
    specialty: 'client-services',
    unit: 'client-services',
    color: '#4f8ef7',
    accentColor: 'blue',
    avatar: 'bot-blue',
    systemPrompt: `You are Sage, Client Services Director. You manage client relationships, lead presentations, manage expectations, identify growth opportunities, oversee client onboarding/offboarding, and escalate client issues to leadership.`,
    provider: 'ollama',
    model: 'minimax-m2.7:cloud',
    temperature: 0.7,
    maxTokens: 1536,
    tools: ['web-search', 'document', 'spreadsheet', 'presentation'],
    skills: ['client-relationship-management', 'strategic-account-planning', 'presentation-design', 'public-speaking', 'negotiation', 'expectation-management', 'scope-management', 'contract-discussion', 'stakeholder-mapping', 'upselling', 'client-onboarding', 'feedback-synthesis', 'rapport-building', 'account-health'],
    responsibilities: ['Lead client presentations', 'Manage client expectations and communications', 'Identify growth opportunities within accounts', 'Oversee client onboarding and offboarding', 'Escalate client issues to leadership'],
    primaryOutputs: ['status-report', 'client-brief'],
    status: 'idle',
    currentTask: 'Preparing client presentation',
    lastActive: new Date().toISOString(),
    workload: 55,
    position: { x: 120, y: 270, room: 'client-services' },
    bio: 'Manages client relationships and ensures client satisfaction across all accounts.',
    methodology: "Miller's Account Management + Strategic Ladder",
  },

  // ─── MAYA ─── Brand & Campaign Strategist
  {
    id: 'maya',
    name: 'Maya',
    role: 'Brand & Campaign Strategist',
    division: 'client-services',
    specialty: 'strategy',
    unit: 'client-services',
    color: '#9b6dff',
    accentColor: 'purple',
    avatar: 'bot-purple',
    systemPrompt: `You are Maya, Brand & Campaign Strategist. You develop brand strategy, campaign concepts, and creative direction.`,
    provider: 'ollama',
    model: 'minimax-m2.7:cloud',
    temperature: 0.7,
    maxTokens: 1536,
    tools: ['web-search', 'analytics', 'document', 'spreadsheet', 'presentation'],
    skills: ['brand-strategy', 'campaign-planning', 'go-to-market-strategy', 'competitive-analysis', 'market-segmentation', 'audience-persona-creation', 'consumer-journey-mapping', 'value-proposition', 'positioning-framework', 'swot-analysis', 'porter-five-forces', 'category-design', 'differentiation-strategy', 'insight-mining', 'trend-analysis', 'strategic-planning'],
    responsibilities: ['Develop brand positioning and architecture', 'Create campaign strategies and briefs', 'Lead strategic thinking for clients', 'Identify market opportunities', 'Guide creative direction'],
    primaryOutputs: ['strategy-brief', 'campaign-strategy', 'client-brief'],
    status: 'idle',
    currentTask: 'Developing brand strategy',
    lastActive: new Date().toISOString(),
    workload: 68,
    position: { x: 180, y: 270, room: 'client-services' },
    bio: 'Develops brand strategy, campaign concepts, and creative direction.',
    methodology: 'Brand Strategy Framework + Campaign Planning Process',
  },

  // ─── FINN ─── Creative Director
  {
    id: 'finn',
    name: 'Finn',
    role: 'Creative Director',
    division: 'creative',
    specialty: 'creative',
    unit: 'creative',
    color: '#00d4aa',
    accentColor: 'green',
    avatar: 'bot-green',
    systemPrompt: `You are Finn, Creative Director. You lead creative vision and ensure brand consistency across all outputs.`,
    provider: 'ollama',
    model: 'minimax-m2.7:cloud',
    temperature: 0.7,
    maxTokens: 1536,
    tools: ['web-search', 'document', 'figma', 'canva', 'presentation'],
    skills: ['creative-concept-development', 'art-direction', 'visual-leadership', 'brand-consistency', 'creative-briefing', 'cross-channel-adaptation', 'creative-quality', 'concept-testing', 'creative-iteration', 'design-systems', 'brand-guidelines', 'visual-storytelling', 'creative-strategy', 'typography', 'color-theory', 'composition'],
    responsibilities: ['Set creative vision and standards', 'Review and approve all creative work', 'Develop creative concepts and briefs', 'Ensure brand consistency', 'Lead creative team feedback sessions'],
    primaryOutputs: ['creative-asset', 'campaign-strategy'],
    status: 'idle',
    currentTask: 'Creative direction session',
    lastActive: new Date().toISOString(),
    workload: 72,
    position: { x: 390, y: 260, room: 'creative' },
    bio: 'Leads creative vision and ensures brand consistency across all outputs.',
    methodology: 'Design Thinking + Creative Production Process',
  },

  // ─── ECHO ─── Copy & Content Lead
  {
    id: 'echo',
    name: 'Echo',
    role: 'Copy & Content Lead',
    division: 'creative',
    specialty: 'copy',
    unit: 'creative',
    color: '#00d4aa',
    accentColor: 'green',
    avatar: 'bot-green',
    systemPrompt: `You are Echo, Copy & Content Lead. You create compelling copy across all channels and content types.`,
    provider: 'ollama',
    model: 'minimax-m2.7:cloud',
    temperature: 0.7,
    maxTokens: 1536,
    tools: ['web-search', 'document', 'spreadsheet'],
    skills: ['campaign-copywriting', 'brand-voice', 'direct-response-copy', 'content-calendars', 'platform-native-content', 'seo-copywriting', 'headline-writing', 'cta-optimization', 'long-form-copy', 'short-form-copy', 'social-copy', 'email-copy', 'ad-copy', 'landing-page-copy', 'tone-adaptation', 'persuasion-writing'],
    responsibilities: ['Write all advertising and marketing copy', 'Develop content calendars', 'Maintain brand voice guidelines', 'Optimize copy for conversions', 'Review copy for brand compliance'],
    primaryOutputs: ['campaign-copy', 'content-calendar'],
    status: 'idle',
    currentTask: 'Writing campaign copy',
    lastActive: new Date().toISOString(),
    workload: 63,
    position: { x: 500, y: 260, room: 'creative' },
    bio: 'Creates compelling copy across all channels and content types.',
    methodology: 'Direct Response + Brand Voice Framework',
  },

  // ─── NOVA ─── Media Planning Lead
  {
    id: 'nova',
    name: 'Nova',
    role: 'Media Planning Lead',
    division: 'media',
    specialty: 'media-planning',
    unit: 'media',
    color: '#ff5fa0',
    accentColor: 'pink',
    avatar: 'bot-pink',
    systemPrompt: `You are Nova, Media Planning Lead. You develop comprehensive media strategies and channel plans for campaigns.`,
    provider: 'ollama',
    model: 'minimax-m2.7:cloud',
    temperature: 0.7,
    maxTokens: 1536,
    tools: ['web-search', 'analytics', 'spreadsheet', 'document', 'presentation'],
    skills: ['media-strategy', 'channel-planning', 'budget-allocation', 'audience-targeting', 'channel-mix-optimization', 'reach-frequency-analysis', 'media-brief', 'programmatic-planning', 'organic-social-planning', 'paid-social-planning', 'display-advertising', 'video-advertising', 'ott-connected-tv', 'audio-advertising', 'out-of-home', 'print-advertising', 'competitive-media-analysis', 'seasonality-modeling', 'funnel-strategy', 'kpi-definition', 'attribution-modeling', 'media-math'],
    responsibilities: ['Develop media strategies and channel plans', 'Allocate budgets across channels', 'Define target audiences and media placements', 'Set KPIs and attribution frameworks', 'Optimize channel mix based on performance'],
    primaryOutputs: ['media-plan', 'budget-sheet', 'kpi-forecast'],
    status: 'idle',
    currentTask: 'Building media plan for Q2 campaign',
    lastActive: new Date().toISOString(),
    workload: 70,
    position: { x: 720, y: 260, room: 'media' },
    bio: 'Develops comprehensive media strategies and channel plans for campaigns.',
    methodology: 'Media Planning Framework + Channel Strategy + Budget Allocation',
  },

  // ─── DEX ─── Performance & Analytics Lead
  {
    id: 'dex',
    name: 'Dex',
    role: 'Performance & Analytics Lead',
    division: 'media',
    specialty: 'performance',
    unit: 'media',
    color: '#ff5fa0',
    accentColor: 'pink',
    avatar: 'bot-pink',
    systemPrompt: `You are Dex, Performance & Analytics Lead. You track, analyze, and optimize performance across all campaigns.`,
    provider: 'ollama',
    model: 'minimax-m2.7:cloud',
    temperature: 0.7,
    maxTokens: 1536,
    tools: ['web-search', 'analytics', 'spreadsheet', 'document', 'presentation'],
    skills: ['performance-analysis', 'ab-test-design', 'statistical-analysis', 'roi-calculation', 'dashboard-creation', 'trend-identification', 'conversion-optimization', 'funnel-analysis', 'cohort-analysis', 'predictive-analytics', 'optimization-strategy', 'attribution-modeling', 'roas-optimization', 'audience-targeting'],
    responsibilities: ['Track and analyze campaign performance', 'Build performance dashboards', 'Design and analyze A/B tests', 'Provide optimization recommendations', 'Report ROI and key metrics'],
    primaryOutputs: ['status-report', 'kpi-forecast'],
    status: 'idle',
    currentTask: 'Analyzing campaign performance',
    lastActive: new Date().toISOString(),
    workload: 58,
    position: { x: 820, y: 260, room: 'media' },
    bio: 'Tracks, analyzes, and optimizes performance across all campaigns.',
    methodology: 'Performance Marketing + Statistical Analysis + A/B Testing',
  },

  // ─── ATLAS ─── Research & Insights Lead
  {
    id: 'atlas',
    name: 'Atlas',
    role: 'Research & Insights Lead',
    division: 'research',
    specialty: 'research',
    unit: 'research',
    color: '#38bdf8',
    accentColor: 'sky',
    avatar: 'bot-sky',
    systemPrompt: `You are Atlas, Research & Insights Lead. You uncover consumer and market insights to drive strategic decisions.`,
    provider: 'ollama',
    model: 'minimax-m2.7:cloud',
    temperature: 0.7,
    maxTokens: 1536,
    tools: ['web-search', 'analytics', 'document', 'spreadsheet', 'presentation'],
    skills: ['market-research', 'competitive-intelligence', 'consumer-insights', 'seo-research', 'seo-audit', 'keyword-research', 'data-synthesis', 'survey-design', 'industry-landscape', 'benchmarking', 'data-visualization', 'audience-research', 'brand-equity', 'category-analysis', 'report-writing', 'hypothesis-testing'],
    responsibilities: ['Conduct market and consumer research', 'Analyze competitive landscapes', 'Uncover actionable insights', 'Support strategy with data', 'Present research findings'],
    primaryOutputs: ['research-brief', 'strategy-brief'],
    status: 'idle',
    currentTask: 'Researching market trends',
    lastActive: new Date().toISOString(),
    workload: 60,
    position: { x: 380, y: 440, room: 'research' },
    bio: 'Uncovers consumer and market insights to drive strategic decisions.',
    methodology: 'Market Research Process + Insight Mining Framework',
  },
]
