import { Agent, AgentTemplate } from './types'

export const OFFICE_ROOMS = [
  { id: 'orchestration', name: 'Mission Control', color: '#9b6dff', x: 380, y: 40, w: 200, h: 100 },
  { id: 'client-services', name: 'Client Services', color: '#4f8ef7', x: 60, y: 180, w: 240, h: 170 },
  { id: 'creative', name: 'Creative Division', color: '#00d4aa', x: 350, y: 180, w: 260, h: 170 },
  { id: 'media', name: 'Media Division', color: '#ff5fa0', x: 660, y: 180, w: 220, h: 170 },
  { id: 'research', name: 'Research Division', color: '#38bdf8', x: 260, y: 390, w: 420, h: 110 },
]

export const AGENT_TEMPLATES: AgentTemplate[] = [
  {
    id: 'brand-strategist',
    name: 'Brand Strategist',
    role: 'Brand & Campaign Strategist',
    division: 'client-services',
    specialty: 'strategy',
    unit: 'client-services',
    color: '#9b6dff',
    accentColor: 'purple',
    avatar: 'bot-purple',
    bio: 'Leads brand strategy, campaign frameworks, and messaging architecture.',
    systemPrompt: `You are a Brand & Campaign Strategist. Turn client goals into sharp positioning, campaign direction, and executable strategy documents.`,
    provider: 'gemini',
    model: 'gemini-2.5-pro',
    temperature: 0.7,
    maxTokens: 1536,
    tools: ['web-search', 'analytics'],
    skills: ['brand strategy', 'campaign planning', 'messaging architecture'],
    responsibilities: ['Define positioning', 'Shape campaign strategy', 'Align messaging to business goals'],
    primaryOutputs: ['strategy-brief', 'campaign-strategy', 'client-brief'],
  },
  {
    id: 'traffic-manager',
    name: 'Traffic Manager',
    role: 'Project / Traffic Manager',
    division: 'client-services',
    specialty: 'project-management',
    unit: 'client-services',
    color: '#ffd166',
    accentColor: 'yellow',
    avatar: 'bot-yellow',
    bio: 'Keeps scopes, schedules, and handoffs on track.',
    systemPrompt: `You are a Project and Traffic Manager. Build timelines, organize dependencies, and keep delivery clean across the agency.`,
    provider: 'ollama',
    model: 'llama3.2:latest',
    temperature: 0.4,
    maxTokens: 1024,
    tools: ['document'],
    skills: ['scheduling', 'resource planning', 'delivery coordination'],
    responsibilities: ['Own timelines', 'Track dependencies', 'Flag blockers'],
    primaryOutputs: ['status-report', 'client-brief'],
  },
  {
    id: 'copywriter',
    name: 'Copy & Content Lead',
    role: 'Copy & Content Lead',
    division: 'creative',
    specialty: 'copy',
    unit: 'creative',
    color: '#ffd166',
    accentColor: 'yellow',
    avatar: 'bot-yellow',
    bio: 'Creates campaign copy, platform-native content, and editorial plans.',
    systemPrompt: `You are a Copy & Content Lead. Produce campaign copy, platform-native content, and content calendars with strong hooks and clear CTAs.`,
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    temperature: 0.8,
    maxTokens: 1280,
    tools: ['web-search', 'social'],
    skills: ['campaign copy', 'content calendars', 'social scripting'],
    responsibilities: ['Write campaign copy', 'Build content calendars', 'Adapt tone by channel'],
    primaryOutputs: ['campaign-copy', 'content-calendar'],
  },
  {
    id: 'visual-designer',
    name: 'Visual Production',
    role: 'Design & Visual Production Lead',
    division: 'creative',
    specialty: 'design',
    unit: 'creative',
    color: '#ff7c42',
    accentColor: 'orange',
    avatar: 'bot-orange',
    bio: 'Translates campaign ideas into visual output and creative asset systems.',
    systemPrompt: `You are a Design & Visual Production Lead. Create creative asset directions, image prompts, and production-ready visual concepts. When image generation is required, prepare prompts optimized for Nano Banana 2.`,
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    temperature: 0.75,
    maxTokens: 1024,
    tools: ['image-gen', 'document'],
    skills: ['art direction', 'visual systems', 'image prompting'],
    responsibilities: ['Create asset directions', 'Prepare Nano Banana 2 prompts', 'Package visual systems'],
    primaryOutputs: ['creative-asset'],
  },
]

export const DEFAULT_AGENTS: Agent[] = [
  {
    id: 'sage',
    name: 'Sage',
    role: 'Client Director',
    division: 'client-services',
    specialty: 'client-services',
    unit: 'client-services',
    color: '#4f8ef7',
    accentColor: 'blue',
    avatar: 'bot-blue',
    systemPrompt: `You are Sage, Client Director. Own the client relationship, sharpen briefs, manage expectations, and keep communication executive-ready.`,
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    temperature: 0.65,
    maxTokens: 1024,
    tools: ['document', 'web-search'],
    skills: ['client leadership', 'briefing', 'presentations'],
    responsibilities: ['Run client communication', 'Translate asks into briefs', 'Prepare status updates'],
    primaryOutputs: ['client-brief', 'status-report'],
    status: 'active',
    currentTask: 'Preparing executive-ready client updates',
    lastActive: new Date().toISOString(),
    workload: 68,
    position: { x: 120, y: 245, room: 'client-services' },
    bio: 'Client lead who keeps relationships confident, clear, and commercially sound.',
  },
  {
    id: 'piper',
    name: 'Piper',
    role: 'Project / Traffic Manager',
    division: 'client-services',
    specialty: 'project-management',
    unit: 'client-services',
    color: '#ffd166',
    accentColor: 'yellow',
    avatar: 'bot-yellow',
    systemPrompt: `You are Piper, Project / Traffic Manager. Build schedules, coordinate handoffs, and keep delivery moving cleanly across teams.`,
    provider: 'ollama',
    model: 'llama3.2:latest',
    temperature: 0.45,
    maxTokens: 896,
    tools: ['document'],
    skills: ['timeline management', 'resourcing', 'delivery tracking'],
    responsibilities: ['Manage schedules', 'Track open tasks', 'Coordinate handoffs'],
    primaryOutputs: ['status-report', 'client-brief'],
    status: 'active',
    currentTask: 'Updating agency schedule and deadlines',
    lastActive: new Date().toISOString(),
    workload: 72,
    position: { x: 180, y: 245, room: 'client-services' },
    bio: 'Traffic manager who turns complexity into a clean delivery rhythm.',
  },
  {
    id: 'maya',
    name: 'Maya',
    role: 'Brand & Campaign Strategist',
    division: 'client-services',
    specialty: 'strategy',
    unit: 'client-services',
    color: '#9b6dff',
    accentColor: 'purple',
    avatar: 'bot-purple',
    systemPrompt: `You are Maya, Brand & Campaign Strategist. Build positioning, brand strategy, campaign direction, messaging architecture, and strategic roadmaps.`,
    provider: 'gemini',
    model: 'gemini-2.5-pro',
    temperature: 0.7,
    maxTokens: 1536,
    tools: ['web-search', 'analytics', 'document'],
    skills: ['brand strategy', 'campaign strategy', 'positioning', 'messaging architecture'],
    responsibilities: ['Lead brand strategy', 'Create campaign strategy', 'Define strategic narrative'],
    primaryOutputs: ['strategy-brief', 'campaign-strategy'],
    status: 'active',
    currentTask: 'Building launch strategy architecture for TechStart',
    lastActive: new Date().toISOString(),
    workload: 81,
    position: { x: 240, y: 245, room: 'client-services' },
    bio: 'Strategy lead who turns client ambition into a coherent market plan.',
  },
  {
    id: 'finn',
    name: 'Finn',
    role: 'Creative Director',
    division: 'creative',
    specialty: 'creative',
    unit: 'creative',
    color: '#00d4aa',
    accentColor: 'cyan',
    avatar: 'bot-cyan',
    systemPrompt: `You are Finn, Creative Director. Turn strategy into memorable campaign concepts, creative systems, and clear art direction.`,
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    temperature: 0.85,
    maxTokens: 1280,
    tools: ['document', 'image-gen'],
    skills: ['creative direction', 'campaign concepts', 'art direction'],
    responsibilities: ['Lead concepts', 'Set creative direction', 'Review creative quality'],
    primaryOutputs: ['creative-asset', 'campaign-copy'],
    status: 'active',
    currentTask: 'Leading concept review for the next campaign wave',
    lastActive: new Date().toISOString(),
    workload: 79,
    position: { x: 430, y: 245, room: 'creative' },
    bio: 'Creative lead who makes campaigns feel distinctive and memorable.',
  },
  {
    id: 'echo',
    name: 'Echo',
    role: 'Copy & Content Lead',
    division: 'creative',
    specialty: 'copy',
    unit: 'creative',
    color: '#ffd166',
    accentColor: 'yellow',
    avatar: 'bot-yellow',
    systemPrompt: `You are Echo, Copy & Content Lead. Produce campaign copy, hooks, scripts, and content calendars tailored to platform behavior and brand voice.`,
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    temperature: 0.82,
    maxTokens: 1280,
    tools: ['web-search', 'social'],
    skills: ['copywriting', 'content calendars', 'scripts', 'CTA writing'],
    responsibilities: ['Write copy', 'Plan content calendars', 'Adapt messaging by channel'],
    primaryOutputs: ['campaign-copy', 'content-calendar'],
    status: 'active',
    currentTask: 'Drafting launch copy and weekly calendar',
    lastActive: new Date().toISOString(),
    workload: 87,
    position: { x: 500, y: 245, room: 'creative' },
    bio: 'Content lead focused on persuasive copy and channel-native storytelling.',
  },
  {
    id: 'nova-studio',
    name: 'Nova Studio',
    role: 'Design & Visual Production Lead',
    division: 'creative',
    specialty: 'design',
    unit: 'creative',
    color: '#ff7c42',
    accentColor: 'orange',
    avatar: 'bot-orange',
    systemPrompt: `You are Nova Studio, Design & Visual Production Lead. Create visual systems, asset directions, and production-ready prompts for Nano Banana 2 when creative generation is required.`,
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    temperature: 0.72,
    maxTokens: 1024,
    tools: ['image-gen', 'document'],
    skills: ['visual systems', 'creative production', 'Nano Banana 2 prompt design'],
    responsibilities: ['Prepare visual output', 'Generate image prompt specs', 'Support creative rollout'],
    primaryOutputs: ['creative-asset'],
    status: 'active',
    currentTask: 'Preparing visual prompt packs for ad variations',
    lastActive: new Date().toISOString(),
    workload: 74,
    position: { x: 570, y: 245, room: 'creative' },
    bio: 'Visual production specialist for creative systems and image-generation-ready outputs.',
  },
  {
    id: 'nova',
    name: 'Nova',
    role: 'Media Planning Lead',
    division: 'media',
    specialty: 'media-planning',
    unit: 'media',
    color: '#ff5fa0',
    accentColor: 'pink',
    avatar: 'bot-pink',
    systemPrompt: `You are Nova, Media Planning Lead. Build channel plans, budget allocations, KPI forecasts, and timing recommendations tied to business goals.`,
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    temperature: 0.55,
    maxTokens: 1400,
    tools: ['analytics', 'document'],
    skills: ['media planning', 'budgeting', 'channel strategy', 'forecasting'],
    responsibilities: ['Build media plans', 'Allocate budget', 'Forecast KPIs'],
    primaryOutputs: ['media-plan', 'budget-sheet', 'kpi-forecast'],
    status: 'active',
    currentTask: 'Balancing channel mix and budget for active launch work',
    lastActive: new Date().toISOString(),
    workload: 76,
    position: { x: 735, y: 245, room: 'media' },
    bio: 'Media planning lead who connects channel choice, budget, and expected return.',
  },
  {
    id: 'dex',
    name: 'Dex',
    role: 'Performance & Media Ops',
    division: 'media',
    specialty: 'performance',
    unit: 'media',
    color: '#4f8ef7',
    accentColor: 'blue',
    avatar: 'bot-blue',
    systemPrompt: `You are Dex, Performance & Media Ops. Turn plans into operational spreadsheets, budget trackers, pacing schedules, and reporting structures.`,
    provider: 'ollama',
    model: 'llama3.2:latest',
    temperature: 0.45,
    maxTokens: 1024,
    tools: ['analytics', 'document', 'code'],
    skills: ['spreadsheet planning', 'budget pacing', 'KPI operations', 'reporting'],
    responsibilities: ['Build spreadsheet outputs', 'Prepare pacing plans', 'Operationalize measurement'],
    primaryOutputs: ['budget-sheet', 'media-plan', 'kpi-forecast'],
    status: 'active',
    currentTask: 'Updating media pacing sheets and KPI assumptions',
    lastActive: new Date().toISOString(),
    workload: 69,
    position: { x: 805, y: 245, room: 'media' },
    bio: 'Media operations specialist who turns plans into executable budgets and reporting systems.',
  },
  {
    id: 'atlas',
    name: 'Atlas',
    role: 'Research, Insights & SEO Lead',
    division: 'research',
    specialty: 'research',
    unit: 'research',
    color: '#38bdf8',
    accentColor: 'blue',
    avatar: 'bot-blue',
    systemPrompt: `You are Atlas, Research, Insights & SEO Lead. Handle competitor scans, audience insight, trend analysis, and SEO audits with actionable recommendations.`,
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    temperature: 0.5,
    maxTokens: 1400,
    tools: ['web-search', 'analytics', 'document'],
    skills: ['competitor research', 'trend analysis', 'seo audits', 'audience insight'],
    responsibilities: ['Research markets and competitors', 'Run SEO audits', 'Surface strategic insights'],
    primaryOutputs: ['research-brief', 'seo-audit', 'strategy-brief'],
    status: 'active',
    currentTask: 'Running insight scans across client categories',
    lastActive: new Date().toISOString(),
    workload: 64,
    position: { x: 450, y: 430, room: 'research' },
    bio: 'Research and SEO lead who turns raw signals into strategic advantage.',
  },
]
