#!/usr/bin/env python3
"""Batch 2 skills: benchmark, bid-management, bottleneck, brand-consistency, brand-equity, brand-guidelines, brand-voice, brief-synthesis, budget-allocation, burndown, campaign-copywriting, campaign-setup, capacity-planning, category-analysis, category-design, change-control, channel-selection"""
import json, os
skills_dir = "/Users/moe/Desktop/Mission Control App/src/config/skills"

def make_skill(skill_id, name, category, difficulty, freedom, trigger, context, instructions, output_template, variables, workflow_steps, checklist, tools, agents, pipelines, tags, description):
    return {
        "$schema": "https://docs.openclaw.ai/skills/schema.json",
        "id": skill_id, "name": name, "description": description,
        "category": category, "difficulty": difficulty, "freedom": freedom,
        "prompts": {"en": {"trigger": trigger, "context": context, "instructions": instructions, "output_template": output_template}},
        "variables": variables, "workflow": {"steps": workflow_steps},
        "examples": [{"input": f"Create output for TechStart - a B2B SaaS fintech company targeting CFOs in UAE", "output": "Full deliverable with all sections filled with B2B context, data-driven insights, and actionable recommendations"}],
        "checklist": checklist, "tools": tools, "agents": agents, "pipelines": pipelines,
        "metadata": {"version": "1.0", "author": "agency", "tags": tags, "lastUpdated": "2026-03-24"}
    }

skills = {}

skills["benchmarking"] = make_skill("benchmarking","Benchmarking","research","intermediate","medium",
    "Use when comparing client performance against industry benchmarks, competitors, or historical performance.",
    "You are a research analyst specializing in competitive benchmarking and performance measurement.",
    "## Benchmarking Workflow\n\n- [ ] 1. Define scope: Identify what to benchmark ({{benchmark_scope}}) against {{industry}} industry\n- [ ] 2. Select benchmarks: Choose KPIs and metrics ({{kpis}}) to compare\n- [ ] 3. Gather data: Collect data from {{data_sources}}\n- [ ] 4. Competitor analysis: Profile {{competitors}} performance\n- [ ] 5. Gap analysis: Identify performance gaps and opportunities\n- [ ] 6. Recommendations: Prioritize actions to close gaps",
    "## Benchmarking Report: {{client_name}}\n\n### Scope: {{benchmark_scope}}\n### Industry: {{industry}}\n\n### KPI Comparison\n| Metric | Client | Industry Avg | Top Quartile | Gap |\n|--------|--------|-------------|--------------|-----|\n| | | | | |\n\n### Competitor Profiles\n| Company | Strength | Weakness | Notable |\n|---------|----------|----------|----------|\n| | | | |\n\n### Gap Analysis\n| Area | Gap Size | Priority |\n|------|----------|----------|\n| | | |\n\n### Recommendations\n1. [Top 3 actions with rationale]",
    [{"name":"client_name","type":"string","required":True,"description":"Client name"},{"name":"benchmark_scope","type":"string","required":True,"description":"What to benchmark"},{"name":"industry","type":"string","required":True,"description":"Industry sector"},{"name":"kpis","type":"string","required":True,"description":"KPIs to compare"},{"name":"data_sources","type":"string","required":True,"description":"Data sources to use"},{"name":"competitors","type":"string","required":True,"description":"Competitors to compare against"}],
    [{"step":1,"name":"Scope Definition","action":"Define what to benchmark and against whom","verify":"Scope is specific and measurable"},{"step":2,"name":"Benchmark Selection","action":"Choose relevant KPIs","verify":"KPIs are industry-standard and available"},{"step":3,"name":"Data Collection","action":"Gather data from sources","verify":"Data is current and comparable"},{"step":4,"name":"Competitor Profiling","action":"Profile competitor performance","verify":"Profiles are factual and sourced"},{"step":5,"name":"Gap Analysis","action":"Identify performance gaps","verify":"Gaps are quantified"},{"step":6,"name":"Recommendations","action":"Prioritize improvement actions","verify":"Actions are specific and impactful"}],
    ["KPIs are industry-standard and comparable","Data sources are credible and current","Competitor data is factual","Gaps are quantified with percentages","Recommendations are prioritized by impact","Report is actionable for leadership"],
    ["spreadsheet","web-search","analytics"],["atlas","dex"],[],"benchmarking","research","competitive-analysis",
    "Compares client performance against industry benchmarks and competitors. Generates gap analysis and prioritized improvement recommendations.")

skills["bid-management"] = make_skill("bid-management","Bid Management","media","intermediate","medium",
    "Use when managing paid search or programmatic bids, optimizing CPC/CPA, or adjusting bidding strategies.",
    "You are a performance media specialist with expertise in bid optimization, auction dynamics, and ROAS improvement.",
    "## Bid Management Workflow\n\n- [ ] 1. Account audit: Review current bid strategy for {{platform}} account\n- [ ] 2. Performance review: Analyze {{time_period}} performance vs targets\n- [ ] 3. Auction analysis: Review competitive landscape and bid landscape\n- [ ] 4. Strategy adjustment: Modify bids based on {{campaign_objective}}\n- [ ] 5. Budget reallocation: Shift budget between campaigns/ad groups\n- [ ] 6. Monitoring plan: Set up alerts and review cadence",
    "## Bid Management Report: {{client_name}}\n\n### Account: {{platform}} | Period: {{time_period}}\n\n### Performance vs Target\n| Campaign | Spend | Revenue | CPA | Target CPA | Status |\n|----------|-------|---------|-----|-----------|--------|\n| | | | | | |\n\n### Bid Strategy Changes\n| Campaign | Current Bid | New Bid | Rationale |\n|----------|-------------|---------|------------|\n| | | | |\n\n### Budget Reallocation\n| From Campaign | To Campaign | Amount | Reason |\n|---------------|-------------|--------|--------|\n| | | | |\n\n### Monitoring Plan\n| Metric | Alert Threshold | Review Frequency |",
    [{"name":"platform","type":"string","required":True,"description":"Platform (Google Ads, Meta, etc.)"},{"name":"client_name","type":"string","required":True,"description":"Client name"},{"name":"time_period","type":"string","required":True,"description":"Analysis period"},{"name":"campaign_objective","type":"string","required":True,"description":"Campaign objective (ROAS, CPA, CPC)"},{"name":"current_targets","type":"string","required":False,"description":"Current performance targets"}],
    [{"step":1,"name":"Account Audit","action":"Review current bid settings and history","verify":"Bid strategy understood"},{"step":2,"name":"Performance Review","action":"Analyze spend, conversions, and efficiency","verify":"Performance vs target clear"},{"step":3,"name":"Auction Analysis","action":"Review competitive landscape and trends","verify":"Bid landscape understood"},{"step":4,"name":"Strategy Adjustment","action":"Modify bids and targeting","verify":"Changes are data-driven"},{"step":5,"name":"Budget Reallocation","action":"Shift budget to best performers","verify":"Reallocation improves overall efficiency"},{"step":6,"name":"Monitoring Plan","action":"Set up alerts and cadence","verify":"Issues caught early"}],
    ["Performance vs target clearly documented","Bid changes are data-driven","Budget reallocation improves overall efficiency","Monitoring plan has specific thresholds","Timeline for review is realistic","Changes are documented with rationale"],
    ["analytics","spreadsheet"],["nova","dex"],[],"bid-management","media","optimization",
    "Manages paid search and programmatic bidding strategies. Optimizes CPC/CPA against targets with data-driven bid adjustments.")

skills["bottleneck-identification"] = make_skill("bottleneck-identification","Bottleneck Identification","operations","intermediate","low",
    "Use when diagnosing workflow bottlenecks, identifying process constraints, or improving throughput in agency operations.",
    "You are an operations analyst specializing in process optimization, throughput analysis, and bottleneck removal.",
    "## Bottleneck Identification Workflow\n\n- [ ] 1. Process mapping: Document the current workflow ({{process_name}})\n- [ ] 2. Throughput analysis: Measure stage-by-stage throughput\n- [ ] 3. Wait time analysis: Identify where work sits idle\n- [ ] 4. Constraint identification: Find the limiting factor ({{constraint_type}})\n- [ ] 5. Impact assessment: Quantify cost of bottleneck\n- [ ] 6. Solution design: Propose ways to eliminate or work around constraint",
    "## Bottleneck Analysis: {{process_name}}\n\n### Process Overview\n| Stage | Avg Duration | Wait Time | Throughput/hr |\n|-------|-------------|-----------|---------------|\n| | | | |\n\n### Bottleneck Identified\n**Location:** [Stage]\n**Type:** {{constraint_type}}\n**Evidence:** [Data supporting this]\n\n### Impact Quantification\n| Metric | Value |\n|--------|-------|\n| Hours lost/week | |\n| Cost impact | |\n| Jobs delayed | |\n\n### Solutions\n| Solution | Effort | Impact | Implementation |\n|----------|--------|--------|---------------|\n| | | | |\n\n### Recommended Action Plan\n1. [Immediate fix]\n2. [Medium-term solution]\n3. [Long-term process change]",
    [{"name":"process_name","type":"string","required":True,"description":"Name of the process to analyze"},{"name":"constraint_type","type":"string","required":True,"description":"Type of constraint (resource, skill,审批, etc.)"},{"name":"volume_data","type":"string","required":True,"description":"Volume and timing data"},{"name":"stages","type":"string","required":True,"description":"Process stages"}],
    [{"step":1,"name":"Process Mapping","action":"Document current workflow stages","verify":"All stages identified and sequenced"},{"step":2,"name":"Throughput Measurement","action":"Measure processing time per stage","verify":"Data is accurate and sampled"},{"step":3,"name":"Wait Time Analysis","action":"Identify where work sits longest","verify":"Wait points confirmed"},{"step":4,"name":"Constraint Identification","action":"Find the limiting factor","verify":"Constraint is real and primary"},{"step":5,"name":"Impact Quantification","action":"Calculate cost of bottleneck","verify":"Impact is quantified"},{"step":6,"name":"Solution Design","action":"Propose elimination strategies","verify":"Solutions address root cause"}],
    ["All process stages mapped and sequenced","Throughput data is accurate","Bottleneck is correctly identified","Impact is quantified in time and cost","Solutions address root cause","Action plan is implementable"],
    ["spreadsheet","analytics"],["piper","sage"],[],"bottleneck","process","operations",
    "Identifies workflow bottlenecks and process constraints. Quantifies impact and proposes solutions to improve throughput.")

skills["brand-consistency"] = make_skill("brand-consistency","Brand Consistency Audit","creative","intermediate","medium",
    "Use when auditing brand consistency across channels, ensuring brand guidelines are followed, or identifying brand dilution.",
    "You are a brand guardian with expertise in brand guidelines, visual consistency, and brand governance.",
    "## Brand Consistency Audit Workflow\n\n- [ ] 1. Guideline review: Analyze {{brand_name}} brand guidelines\n- [ ] 2. Channel audit: Review assets across {{channels}}\n- [ ] 3. Consistency scoring: Rate each element ({{scoring_criteria}})\n- [ ] 4. Violation cataloging: Document deviations and their impact\n- [ ] 5. Root cause analysis: Identify why inconsistencies occur\n- [ ] 6. Remediation plan: Create action plan to restore consistency",
    "## Brand Consistency Audit: {{brand_name}}\n\n### Channels Audited: {{channels}}\n\n### Consistency Scores\n| Element | Score (/10) | Finding |\n|---------|-------------|---------|\n| Logo usage | | |\n| Color palette | | |\n| Typography | | |\n| Tone of voice | | |\n| Imagery style | | |\n| Message consistency | | |\n\n### Violations Found\n| Channel | Element | Violation | Severity | Impact |\n|---------|---------|-----------|----------|--------|\n| | | | | |\n\n### Root Causes\n1. [Why violations occurred]\n\n### Remediation Plan\n| Action | Owner | Timeline | Priority |\n|--------|-------|----------|----------|\n| | | | |",
    [{"name":"brand_name","type":"string","required":True,"description":"Brand to audit"},{"name":"channels","type":"string","required":True,"description":"Channels to audit"},{"name":"scoring_criteria","type":"string","required":True,"description":"Scoring criteria for consistency"},{"name":"guideline_ref","type":"string","required":False,"description":"Brand guidelines reference"}],
    [{"step":1,"name":"Guideline Review","action":"Analyze brand guidelines","verify":"Guidelines are clear and specific"},{"step":2,"name":"Channel Audit","action":"Review assets across channels","verify":"All key channels covered"},{"step":3,"name":"Consistency Scoring","action":"Rate each brand element","verify":"Scoring is consistent and objective"},{"step":4,"name":"Violation Cataloging","action":"Document all deviations","verify":"Violations are specific and sourced"},{"step":5,"name":"Root Cause Analysis","action":"Identify why violations occurred","verify":"Root causes are identified"},{"step":6,"name":"Remediation Plan","action":"Create action plan","verify":"Plan is implementable"}],
    ["All key channels audited","Consistency scoring is objective","Violations are specific and documented","Root causes identified","Remediation plan has clear owners","Timeline is realistic"],
    ["spreadsheet","document"],["finn","sage"],[],"brand","consistency","audit",
    "Audits brand consistency across channels, scores elements, and creates remediation plans to restore brand integrity.")

skills["brand-equity"] = make_skill("brand-equity","Brand Equity Analysis","strategy","advanced","medium",
    "Use when measuring brand equity, tracking brand health over time, or assessing brand value for a client.",
    "You are a brand strategist with expertise in brand equity measurement, brand valuation, and brand health tracking.",
    "## Brand Equity Analysis Workflow\n\n- [ ] 1. Asset identification: List all brand equity drivers for {{brand_name}}\n- [ ] 2. Awareness measurement: Assess aided and unaided awareness in {{market}}\n- [ ] 3. Perception analysis: Evaluate brand associations and sentiment\n- [ ] 4. Loyalty assessment: Measure repeat purchase and advocacy\n- [ ] 5. Equity calculation: Estimate financial value of brand equity\n- [ ] 6. Comparison: Benchmark against {{competitors}}",
    "## Brand Equity Analysis: {{brand_name}}\n\n### Market: {{market}} | Period: {{time_period}}\n\n### Brand Equity Components\n| Component | Score (/10) | Change vs Prior | Industry Benchmark |\n|-----------|-------------|-----------------|-------------------|\n| Awareness | | | |\n| Associations | | | |\n| Quality perception | | | |\n| Loyalty | | | |\n| Advocacy | | | |\n\n### Awareness Metrics\n| Type | Current | Target | Gap |\n|------|---------|--------|-----|\n| Aided awareness | | | |\n| Unaided awareness | | | |\n\n### Brand Association Map\n| Attribute | Score | Favorability | Distinctiveness |\n|-----------|-------|--------------|-----------------|\n| | | | |\n\n### Financial Brand Equity Estimate\n| Component | Value |\n|-----------|-------|\n| Brand strength multiplier | |\n| Brand revenue | |\n| Brand value estimate | |\n\n### Competitive Position\n[Brand equity vs competitors chart summary]\n\n### Recommendations\n1. [Priority actions to build equity]",
    [{"name":"brand_name","type":"string","required":True,"description":"Brand to analyze"},{"name":"market","type":"string","required":True,"description":"Market geography"},{"name":"time_period","type":"string","required":True,"description":"Analysis period"},{"name":"competitors","type":"string","required":True,"description":"Competitors to compare"}],
    [{"step":1,"name":"Asset Identification","action":"List all brand equity drivers","verify":"All key components covered"},{"step":2,"name":"Awareness Measurement","action":"Assess awareness levels","verify":"Methodology is sound"},{"step":3,"name":"Perception Analysis","action":"Evaluate associations and sentiment","verify":"Data is current"},{"step":4,"name":"Loyalty Assessment","action":"Measure loyalty metrics","verify":"Metrics are meaningful"},{"step":5,"name":"Equity Calculation","action":"Estimate financial value","verify":"Methodology is defensible"},{"step":6,"name":"Comparison","action":"Benchmark against competitors","verify":"Comparison is fair"}],
    ["All brand equity components covered","Awareness methodology is sound","Perception data is current","Financial estimate is methodology-driven","Comparison is fair and contextual","Recommendations are strategic"],
    ["spreadsheet","analytics","web-search"],["maya","atlas"],[],"brand-equity","brand-health","strategy",
    "Measures brand equity across awareness, perception, and loyalty components. Calculates financial brand value and benchmarks against competitors.")

skills["brand-guidelines"] = make_skill("brand-guidelines","Brand Guidelines Development","creative","advanced","medium",
    "Use when creating comprehensive brand guidelines, updating existing guidelines, or building brand documentation for new clients.",
    "You are a brand strategist with expertise in brand guidelines, visual identity systems, and brand governance documentation.",
    "## Brand Guidelines Development Workflow\n\n- [ ] 1. Discovery: Review existing brand assets and history for {{brand_name}}\n- [ ] 2. Identity system: Define logo usage, color, typography ({{identity_elements}})\n- [ ] 3. Voice guidelines: Establish tone, style, and messaging principles\n- [ ] 4. Application rules: Document do is and do nots across use cases\n- [ ] 5. Asset library: Specify required brand assets and templates\n- [ ] 6. Governance: Create approval and exception processes",
    "## Brand Guidelines: {{brand_name}}\n\n### 1. Brand Overview\n- **Brand mission:**\n- **Brand vision:**\n- **Brand values:**\n\n### 2. Logo System\n| Application | Specification | Minimum Size |\n|-------------|--------------|---------------|\n| Primary logo | | |\n| Horizontal | | |\n| Stacked | | |\n| Icon only | | |\n\n**Clear space:** [Specification]\n**Incorrect usage:** [Examples]\n\n### 3. Color Palette\n| Color | Hex | Pantone | CMYK | RGB | Usage |\n|-------|-----|---------|------|-----|-------|\n| Primary | | | | | |\n| Secondary | | | | | |\n| Accent | | | | | |\n| Neutral | | | | | |\n\n### 4. Typography\n| Element | Font | Weight | Size |\n|---------|------|--------|------|\n| H1 | | | |\n| H2 | | | |\n| Body | | | |\n| Caption | | | |\n\n### 5. Tone of Voice\n- **Personality:**\n- **Tone variations:**\n- **Vocabulary do is and do nots:**\n\n### 6. Imagery Style\n- **Photography:**\n- **Illustration:**\n- **Iconography:**\n\n### 7. Application Examples\n[Logo on light/dark backgrounds, etc.]\n\n### 8. Governance\n- **Approval process:**\n- **Exception requests:**\n- **Contact:**",
    [{"name":"brand_name","type":"string","required":True,"description":"Brand name"},{"name":"industry","type":"string","required":True,"description":"Industry"},{"name":"identity_elements","type":"string","required":True,"description":"Identity elements to include"},{"name":"existing_assets","type":"string","required":False,"description":"Existing brand assets"}],
    [{"step":1,"name":"Discovery","action":"Review brand history and assets","verify":"All existing assets catalogued"},{"step":2,"name":"Identity System","action":"Define logo, color, typography","verify":"System is cohesive and usable"},{"step":3,"name":"Voice Guidelines","action":"Establish tone and messaging rules","verify":"Voice is distinctive and consistent"},{"step":4,"name":"Application Rules","action":"Document usage rules","verify":"Rules are clear and actionable"},{"step":5,"name":"Asset Library","action":"Specify required assets","verify":"Assets are producible"},{"step":6,"name":"Governance","action":"Create approval process","verify":"Process is practical"}],
    ["Logo system is comprehensive and clear","Color palette is cohesive and reproducible","Typography is distinctive and readable","Tone of voice is specific and actionable","Application rules cover key use cases","Guidelines are implementable by third parties"],
    ["document","presentation"],["finn","sage"],[],"brand-guidelines","brand","identity",
    "Creates comprehensive brand guidelines including logo, color, typography, voice, and application rules.")

skills["brand-voice"] = make_skill("brand-voice","Brand Voice Development","creative","intermediate","medium",
    "Use when developing brand voice and tone guidelines, adapting brand voice for different channels, or training teams on brand voice.",
    "You are a copy strategist specializing in brand voice development, tone adaptation, and messaging frameworks.",
    "## Brand Voice Development Workflow\n\n- [ ] 1. Voice audit: Review existing brand communications for {{brand_name}}\n- [ ] 2. Personality definition: Define brand personality traits ({{personality_traits}})\n- [ ] 3. Voice dimensions: Set specific dimensions (formal-casual, playful-serious, etc.)\n- [ ] 4. Channel adaptation: Map how voice adapts across {{channels}}\n- [ ] 5. Writing guidelines: Create do is, do nots, and examples\n- [ ] 6. Implementation plan: Train team and set governance",
    "## Brand Voice Guidelines: {{brand_name}}\n\n### Brand Personality\n**Archetype:** {{archetype}}\n**Traits:** {{personality_traits}}\n\n### Voice Spectrum\n| Dimension | Score (1-10) | Definition |\n|-----------|-------------|------------|\n| Formal ←→ Casual | | |\n| Serious ←→ Playful | | |\n| Reserved ←→ Bold | | |\n| Traditional ←→ Innovative | | |\n\n### Core Voice Principles\n1. [Principle 1 with rationale]\n2. [Principle 2 with rationale]\n3. [Principle 3 with rationale]\n\n### Do's and Don'ts\n**DO:**\n- [ ] \n\n**DON'T:**\n- [ ] \n\n### Channel Voice Adaptation\n| Channel | Voice Adjustments | Examples |\n|---------|------------------|----------|\n| Website | | |\n| Social | | |\n| Email | | |\n| Print | | |\n\n### Example Transformations\n| Message | Before (Wrong) | After (Right) |\n|---------|---------------|---------------|\n| | | |",
    [{"name":"brand_name","type":"string","required":True,"description":"Brand name"},{"name":"industry","type":"string","required":True,"description":"Industry"},{"name":"personality_traits","type":"string","required":True,"description":"Desired personality traits"},{"name":"archetype","type":"string","required":False,"description":"Brand archetype"},{"name":"channels","type":"string","required":False,"description":"Channels to adapt voice for"}],
    [{"step":1,"name":"Voice Audit","action":"Review existing communications","verify":"Current voice understood"},{"step":2,"name":"Personality Definition","action":"Define brand personality","verify":"Personality is distinctive and authentic"},{"step":3,"name":"Voice Dimensions","action":"Set specific voice dimensions","verify":"Dimensions are measurable"},{"step":4,"name":"Channel Adaptation","action":"Map voice adaptations","verify":"Adaptations are appropriate"},{"step":5,"name":"Writing Guidelines","action":"Create do's and don'ts","verify":"Guidelines are actionable"},{"step":6,"name":"Implementation","action":"Plan training and governance","verify":"Plan is executable"}],
    ["Voice is distinctive and ownable","Dimensions are specific and measurable","Channel adaptations are appropriate","Do's and don'ts are clear","Examples are illustrative and realistic","Implementation plan is practical"],
    ["document","presentation"],["finn","echo"],[],"brand-voice","copywriting","tone",
    "Develops brand voice and tone guidelines with personality traits, voice dimensions, and channel-specific adaptations.")

skills["brief-synthesis"] = make_skill("brief-synthesis","Brief Synthesis","operations","intermediate","medium",
    "Use when synthesizing campaign briefs from client intake, distilling multiple inputs into a clear brief, or formalizing scattered requirements into a structured brief.",
    "You are a client services specialist skilled at distilling complex client requirements into clear, actionable briefs.",
    "## Brief Synthesis Workflow\n\n- [ ] 1. Input collection: Gather all available inputs ({{input_sources}})\n- [ ] 2. Key insight extraction: Identify the core business problem\n- [ ] 3. Requirement mapping: Map objectives, audience, and constraints\n- [ ] 4. Gap identification: Note what is missing and needs probing\n- [ ] 5. Brief drafting: Structure into standard brief format\n- [ ] 6. Client validation: Confirm understanding with {{client_name}}",
    "## Campaign Brief: {{campaign_name}}\n\n### Client: {{client_name}}\n\n### Business Objective\n[What is the client trying to achieve?]\n\n### Target Audience\n| Segment | Description | Key Insight |\n|---------|-------------|-------------|\n| Primary | | |\n| Secondary | | |\n\n### Key Messages\n1. [Primary message]\n2. [Supporting message]\n3. [Tertiary message]\n\n### Campaign Parameters\n| Element | Specification |\n|---------|---------------|\n| Budget | {{budget}} |\n| Timeline | {{timeline}} |\n| Channels | {{channels}} |\n| Geography | {{geography}} |\n| KPIs | {{kpis}} |\n\n### Mandatories\n- [What MUST be included/avoided]\n\n### Known Constraints\n[Budget, legal, brand safety, etc.]\n\n### Open Questions\n[Items needing client input]\n\n### Fit with Agency\n[Why this brief suits agency strengths]",
    [{"name":"campaign_name","type":"string","required":True,"description":"Campaign or project name"},{"name":"client_name","type":"string","required":True,"description":"Client name"},{"name":"input_sources","type":"string","required":True,"description":"Available input sources"},{"name":"budget","type":"string","required":True,"description":"Budget range"},{"name":"timeline","type":"string","required":True,"description":"Timeline"}],
    [{"step":1,"name":"Input Collection","action":"Gather all available inputs","verify":"No key input missed"},{"step":2,"name":"Insight Extraction","action":"Identify core business problem","verify":"Problem is clearly stated"},{"step":3,"name":"Requirement Mapping","action":"Map all requirements","verify":"Requirements are complete"},{"step":4,"name":"Gap Identification","action":"Note missing information","verify":"Gaps are explicitly listed"},{"step":5,"name":"Brief Drafting","action":"Structure into standard format","verify":"Brief is clear and actionable"},{"step":6,"name":"Validation","action":"Confirm with client","verify":"Client agrees with brief"}],
    ["All available inputs synthesized","Core business problem clearly stated","Requirements are complete and non-contradictory","Gaps are explicitly flagged","Brief is actionable for creative team","Client validation obtained"],
    ["document","spreadsheet"],["sage","maya"],["campaign-brief"],"brief","client-services","planning",
    "Synthesizes multiple client inputs into clear, structured campaign briefs ready for creative and media teams.")

skills["budget-allocation"] = make_skill("budget-allocation","Budget Allocation","media","intermediate","medium",
    "Use when allocating marketing budgets across channels, campaigns, or time periods for clients.",
    "You are a media strategist specializing in budget optimization, channel mix, and financial planning for marketing.",
    "## Budget Allocation Workflow\n\n- [ ] 1. Objective alignment: Match budget to {{campaign_objectives}}\n- [ ] 2. Historical analysis: Review {{client_name}} past performance by channel\n- [ ] 3. Channel benchmarks: Reference industry benchmarks for {{industry}}\n- [ ] 4. Allocation model: Distribute budget using {{allocation_logic}}\n- [ ] 5. Scenario planning: Model optimistic and conservative scenarios\n- [ ] 6. Documentation: Create detailed budget narrative",
    "## Budget Allocation: {{client_name}}\n\n### Total Budget: {{total_budget}} | Period: {{time_period}}\n\n### Objectives: {{campaign_objectives}}\n\n### Proposed Allocation\n| Channel | Budget | % of Total | Expected ROI | Rationale |\n|---------|--------|------------|--------------|------------|\n| | | | | |\n\n### Allocation Rationale\n[Explanation of why each channel received its allocation]\n\n### Historical vs Proposed\n| Channel | Last Period | Proposed | Change | Reason |\n|---------|-------------|----------|--------|--------|\n| | | | | |\n\n### Scenario Analysis\n| Scenario | Assumption | Channel Impact |\n|----------|------------|----------------|\n| Conservative | -20% budget | |\n| Aggressive | +20% budget | |\n\n### Monthly Pacing\n| Month | Planned Spend | % of Budget |\n|-------|--------------|---------------|\n| | | |",
    [{"name":"client_name","type":"string","required":True,"description":"Client name"},{"name":"total_budget","type":"string","required":True,"description":"Total budget"},{"name":"time_period","type":"string","required":True,"description":"Period"},{"name":"campaign_objectives","type":"string","required":True,"description":"Campaign objectives"},{"name":"industry","type":"string","required":True,"description":"Industry"},{"name":"allocation_logic","type":"string","required":False,"description":"Allocation methodology"}],
    [{"step":1,"name":"Objective Alignment","action":"Match budget to objectives","verify":"Budget serves stated goals"},{"step":2,"name":"Historical Analysis","action":"Review past channel performance","verify":"Historical data is considered"},{"step":3,"name":"Benchmark Research","action":"Reference industry standards","verify":"Benchmarks are relevant"},{"step":4,"name":"Allocation Model","action":"Distribute budget across channels","verify":"Allocation is logical and justified"},{"step":5,"name":"Scenario Planning","action":"Model different scenarios","verify":"Scenarios are realistic"},{"step":6,"name":"Documentation","action":"Create budget narrative","verify":"Rationale is clear"}],
    ["Budget serves stated objectives","Allocation is based on data and rationale","Historical performance considered","Scenario analysis is realistic","Monthly pacing is even and achievable","Recommendations are clear"],
    ["spreadsheet","analytics"],["nova","dex"],["media-plan"],"budget","media","allocation",
    "Allocates marketing budgets across channels with data-driven rationale, scenario analysis, and monthly pacing.")

skills["burndown-tracking"] = make_skill("burndown-tracking","Burndown Tracking","operations","intermediate","medium",
    "Use when tracking sprint or project burndown charts, monitoring team velocity, or forecasting delivery dates.",
    "You are an agile coach and project manager specializing in burndown analysis and delivery forecasting.",
    "## Burndown Tracking Workflow\n\n- [ ] 1. Baseline setup: Establish scope and commitment for {{sprint_name}}\n- [ ] 2. Daily tracking: Monitor daily progress vs ideal burndown\n- [ ] 3. Variance analysis: Identify deviations and their causes\n- [ ] 4. Forecast update: Revise end-date based on current velocity\n- [ ] 5. Risk flagging: Identify risks to delivery\n- [ ] 6. Reporting: Update stakeholders with current status",
    "## Burndown Report: {{sprint_name}}\n\n### Sprint Period: {{start_date}} - {{end_date}}\n### Team: {{team_name}}\n\n### Current Status\n| Metric | Value |\n|--------|-------|\n| Total Points | |\n| Completed | |\n| Remaining | |\n| Days Remaining | |\n| Current Velocity | |\n| Required Velocity | |\n\n### Burndown Chart Summary\n| Day | Ideal | Actual | Variance |\n|-----|-------|--------|----------|\n| D1 | | | |\n| D5 | | | |\n| D10 | | | |\n| Current | | | |\n\n### Variance Analysis\n[Why is actual ahead/behind ideal?]\n\n### Forecast\n| Scenario | Completion Date | Confidence |\n|----------|-----------------|------------|\n| Current pace | | |\n| Required pace | | |\n| Best case | | |\n\n### Risks to Delivery\n| Risk | Impact | Mitigation |\n|------|--------|------------|\n| | | |",
    [{"name":"sprint_name","type":"string","required":True,"description":"Sprint or project name"},{"name":"start_date","type":"string","required":True,"description":"Start date"},{"name":"end_date","type":"string","required":True,"description":"End date"},{"name":"team_name","type":"string","required":True,"description":"Team name"},{"name":"total_points","type":"string","required":True,"description":"Total story points"}],
    [{"step":1,"name":"Baseline Setup","action":"Confirm sprint scope and commitment","verify":"Commitment is documented"},{"step":2,"name":"Daily Tracking","action":"Monitor daily progress","verify":"Data is current"},{"step":3,"name":"Variance Analysis","action":"Identify deviations","verify":"Causes are understood"},{"step":4,"name":"Forecast Update","action":"Revise delivery estimate","verify":"Forecast is realistic"},{"step":5,"name":"Risk Flagging","action":"Identify delivery risks","verify":"Risks are material"},{"step":6,"name":"Reporting","action":"Update stakeholders","verify":"Report is clear"}],
    ["Burndown data is current","Variance analysis identifies real causes","Forecast is data-driven","Risks are material and mitigations proposed","Report is clear for non-technical readers","Action items are specific"],
    ["spreadsheet"],["piper"],[],"burndown","agile","project-management",
    "Tracks sprint burndown and forecasts delivery dates based on current velocity and variance analysis.")

skills["campaign-copywriting"] = make_skill("campaign-copywriting","Campaign Copywriting","creative","intermediate","high",
    "Use when writing campaign copy across multiple formats, channels, and touchpoints for a unified campaign.",
    "You are a senior copywriter with expertise in integrated campaign messaging, multi-channel copy, and brand storytelling.",
    "## Campaign Copywriting Workflow\n\n- [ ] 1. Campaign brief review: Align to {{campaign_objective}} and {{key_message}}\n- [ ] 2. Channel mapping: Plan copy for each {{channels}} in the campaign\n- [ ] 3. Core narrative: Develop the central story and messaging hierarchy\n- [ ] 4. Format adaptation: Write copy for each format and channel\n- [ ] 5. Consistency check: Ensure brand voice consistency throughout\n- [ ] 6. CTA development: Create unified call-to-action framework",
    "## Campaign Copy: {{client_name}} - {{campaign_name}}\n\n### Brief Alignment\n- **Objective:** {{campaign_objective}}\n- **Key message:** {{key_message}}\n- **Channels:** {{channels}}\n\n### Core Narrative\n[2-3 sentences defining the central story]\n\n### Messaging Hierarchy\n1. **Primary message:** [Main idea]\n2. **Secondary message:** [Supporting idea]\n3. **Tertiary message:** [Proof points]\n\n### Channel Copy\n\n#### {{channel_1}}\n**Headline:**\n[Headline text]\n\n**Body:**\n[Body copy - 2-3 paragraphs]\n\n**CTA:** [Button/link text]\n\n---\n\n#### {{channel_2}}\n[Same structure]\n\n### CTA Framework\n| Channel | CTA Text | CTA Type |\n|---------|----------|----------|\n| | | |\n\n### Tone Notes\n[Specific tone directions for this campaign]",
    [{"name":"client_name","type":"string","required":True,"description":"Client name"},{"name":"campaign_name","type":"string","required":True,"description":"Campaign name"},{"name":"campaign_objective","type":"string","required":True,"description":"Campaign objective"},{"name":"key_message","type":"string","required":True,"description":"Primary key message"},{"name":"channels","type":"string","required":True,"description":"Channels to write for"}],
    [{"step":1,"name":"Brief Review","action":"Align to campaign brief","verify":"Brief requirements are met"},{"step":2,"name":"Channel Mapping","action":"Plan copy approach per channel","verify":"Approach fits each channel"},{"step":3,"name":"Core Narrative","action":"Develop central story","verify":"Story is compelling and ownable"},{"step":4,"name":"Format Adaptation","action":"Write copy for each format","verify":"Copy is channel-appropriate"},{"step":5,"name":"Consistency Check","action":"Ensure brand voice consistency","verify":"Voice is consistent"},{"step":6,"name":"CTA Development","action":"Create unified CTA framework","verify":"CTAs drive desired action"}],
    ["Copy aligns to brief objectives","Central narrative is compelling","Each channel gets appropriate copy","Brand voice is consistent","CTA framework is unified","Copy is ready for production"],
    ["document"],["finn","echo"],[],"campaign-copy","copywriting","creative",
    "Writes integrated campaign copy across multiple channels with unified messaging hierarchy and CTA framework.")

skills["campaign-setup"] = make_skill("campaign-setup","Campaign Setup","media","intermediate","medium",
    "Use when setting up new advertising campaigns in platforms like Google Ads, Meta, or LinkedIn.",
    "You are a performance media specialist with expertise in campaign architecture, platform setup, and conversion tracking.",
    "## Campaign Setup Workflow\n\n- [ ] 1. Structure design: Plan campaign hierarchy ({{campaign_structure}})\n- [ ] 2. Platform configuration: Set up campaign in {{platform}}\n- [ ] 3. Targeting setup: Configure audience targeting parameters\n- [ ] 4. Budget settings: Set budget and bidding strategy\n- [ ] 5. Tracking implementation: Install and verify conversion tracking\n- [ ] 6. QA check: Verify all settings before launch",
    "## Campaign Setup: {{client_name}} - {{campaign_name}}\n\n### Platform: {{platform}}\n\n### Campaign Structure\n| Level | Name | Budget | Bidding |\n|-------|------|--------|---------|\n| Campaign | | | |\n| Ad Set 1 | | | |\n| Ad Set 2 | | | |\n| Ad 1 | | | |\n| Ad 2 | | | |\n\n### Targeting Configuration\n| Parameter | Setting |\n|-----------|---------|\n| Location | |\n| Age | |\n| Gender | |\n| Interests | |\n| Placements | |\n| Exclusions | |\n\n### Budget and Bidding\n| Setting | Value |\n|---------|-------|\n| Budget type | |\n| Daily budget | |\n| Bidding strategy | |\n| Target CPA/ROAS | |\n\n### Tracking Plan\n| Event | Tracking Method | Verification |\n|-------|----------------|--------------|\n| | | |\n\n### Launch Checklist\n- [ ] All ad copy reviewed\n- [ ] Targeting verified\n- [ ] Tracking tested\n- [ ] Budget approved\n- [ ] Client sign-off obtained",
    [{"name":"platform","type":"string","required":True,"description":"Platform"},{"name":"client_name","type":"string","required":True,"description":"Client name"},{"name":"campaign_name","type":"string","required":True,"description":"Campaign name"},{"name":"campaign_structure","type":"string","required":True,"description":"Campaign structure"},{"name":"targeting_params","type":"string","required":True,"description":"Targeting parameters"}],
    [{"step":1,"name":"Structure Design","action":"Plan campaign and ad group hierarchy","verify":"Structure supports objectives"},{"step":2,"name":"Platform Configuration","action":"Set up campaign in platform","verify":"Settings match brief"},{"step":3,"name":"Targeting Setup","action":"Configure audience targeting","verify":"Targeting is precise"},{"step":4,"name":"Budget Settings","action":"Set budget and bidding","verify":"Budget supports goals"},{"step":5,"name":"Tracking Implementation","action":"Install conversion tracking","verify":"Tracking is verified"},{"step":6,"name":"QA Check","action":"Verify all settings","verify":"Campaign is ready to launch"}],
    ["Campaign structure supports objectives","Targeting is precise and appropriate","Budget is set correctly","Conversion tracking is verified","Launch checklist is complete","All approvals obtained"],
    ["analytics","spreadsheet"],["nova"],[],"campaign-setup","media","advertising",
    "Sets up advertising campaigns in platforms with correct structure, targeting, budget, and conversion tracking.")

skills["capacity-planning"] = make_skill("capacity-planning","Capacity Planning","operations","intermediate","medium",
    "Use when planning team capacity, forecasting resource needs, or managing workload distribution across the agency.",
    "You are an operations manager specializing in resource planning, team capacity, and workload management.",
    "## Capacity Planning Workflow\n\n- [ ] 1. Demand forecasting: Estimate workload from {{upcoming_projects}}\n- [ ] 2. Capacity inventory: Assess available team capacity ({{team_members}})\n- [ ] 3. Gap analysis: Identify periods of over/under capacity\n- [ ] 4. Scenario modeling: Model different demand scenarios\n- [ ] 5. Hiring/outsourcing plan: Address capacity gaps\n- [ ] 6. Monitoring: Set up capacity tracking and alerts",
    "## Capacity Plan: {{team_name}}\n\n### Period: {{time_period}}\n\n### Team Capacity\n| Role | Headcount | Available Hours/Week | Total Capacity |\n|------|-----------|---------------------|----------------|\n| | | | |\n\n### Demand Forecast\n| Project/Client | Hours Needed | Priority | Timeline |\n|----------------|-------------|----------|----------|\n| | | | |\n\n### Capacity vs Demand\n| Week | Demand (hrs) | Capacity (hrs) | Gap | Status |\n|------|-------------|----------------|-----|--------|\n| W1 | | | | |\n| W2 | | | | |\n| W3 | | | | |\n\n### Gap Analysis\n[Where is capacity insufficient?]\n\n### Solutions\n| Gap | Solution | Effort | Cost |\n|-----|----------|--------|------|\n| | | | |\n\n### Staffing Recommendations\n1. [Immediate actions]\n2. [Short-term hiring/outsourcing]\n3. [Long-term capacity plan]",
    [{"name":"team_name","type":"string","required":True,"description":"Team or department"},{"name":"time_period","type":"string","required":True,"description":"Planning period"},{"name":"upcoming_projects","type":"string","required":True,"description":"Upcoming projects and hours needed"},{"name":"team_members","type":"string","required":True,"description":"Team members and availability"}],
    [{"step":1,"name":"Demand Forecasting","action":"Estimate workload","verify":"Estimates are realistic"},{"step":2,"name":"Capacity Inventory","action":"Assess available capacity","verify":"Capacity is accurately measured"},{"step":3,"name":"Gap Analysis","action":"Identify capacity gaps","verify":"Gaps are quantified"},{"step":4,"name":"Scenario Modeling","action":"Model different scenarios","verify":"Scenarios are realistic"},{"step":5,"name":"Solution Design","action":"Address gaps","verify":"Solutions are practical"},{"step":6,"name":"Monitoring Setup","action":"Set up tracking","verify":"Alerts are configured"}],
    ["Demand estimates are realistic","Capacity is accurately measured","Gaps are clearly identified","Solutions address root causes","Monitoring plan is set up","Timeline is communicated"],
    ["spreadsheet"],["piper","sage"],[],"capacity","planning","operations",
    "Plans team capacity against project demand, identifies gaps, and creates solutions for resource optimization.")

skills["category-analysis"] = make_skill("category-analysis","Category Analysis","research","advanced","medium",
    "Use when analyzing product or service categories for market entry, category positioning, or competitive landscape within a category.",
    "You are a market research analyst specializing in category dynamics, competitive analysis, and market sizing.",
    "## Category Analysis Workflow\n\n- [ ] 1. Category definition: Define the category boundaries for {{category_name}}\n- [ ] 2. Market sizing: Estimate total market size ({{market_size_methodology}})\n- [ ] 3. Growth analysis: Assess category growth trends and drivers\n- [ ] 4. Competitive landscape: Map all players in the category\n- [ ] 5. Consumer behavior: Understand how consumers shop this category\n- [ ] 6. Opportunity mapping: Identify white space and entry opportunities",
    "## Category Analysis: {{category_name}}\n\n### Market: {{market_geography}}\n\n### Category Definition\n[What is included/excluded in this category]\n\n### Market Size\n| Metric | Value | Source |\n|--------|-------|--------|\n| TAM | | |\n| SAM | | |\n| SOM | | |\n\n### Growth Trends\n| Year | Market Size | Growth Rate |\n|------|-------------|-------------|\n| | | |\n\n### Competitive Landscape\n| Player | Market Share | Strength | Weakness | Price Range |\n|--------|-------------|----------|----------|-------------|\n| | | | | |\n\n### Consumer Behavior\n- **Purchase frequency:**\n- **Decision factors:**\n- **Channel preferences:**\n- **Key decision moments:**\n\n### White Space Opportunities\n| Opportunity | Size | Difficulty | Fit |\n|-------------|------|------------|-----|\n| | | | |\n\n### Entry Strategy Recommendations\n1. [Priority entry approach]\n2. [Differentiator]\n3. [Timeline]",
    [{"name":"category_name","type":"string","required":True,"description":"Category to analyze"},{"name":"market_geography","type":"string","required":True,"description":"Market geography"},{"name":"market_size_methodology","type":"string","required":True,"description":"Market sizing approach"},{"name":"competitors","type":"string","required":True,"description":"Known competitors"}],
    [{"step":1,"name":"Category Definition","action":"Define category boundaries","verify":"Definition is clear and useful"},{"step":2,"name":"Market Sizing","action":"Estimate market size","verify":"Methodology is sound"},{"step":3,"name":"Growth Analysis","action":"Assess growth trends","verify":"Trends are documented"},{"step":4,"name":"Competitive Mapping","action":"Map competitive landscape","verify":"All key players included"},{"step":5,"name":"Consumer Analysis","action":"Understand consumer behavior","verify":"Behavior is documented"},{"step":6,"name":"Opportunity Mapping","action":"Identify white space","verify":"Opportunities are real"}],
    ["Category is clearly defined","Market sizing is methodology-driven","Competitive landscape is comprehensive","Consumer behavior is understood","White space is real and quantified","Recommendations are actionable"],
    ["spreadsheet","web-search","analytics"],["atlas","nova"],[],"category","market-research","competitive-analysis",
    "Analyzes product categories including market sizing, competitive landscape, consumer behavior, and entry opportunities.")

skills["category-design"] = make_skill("category-design","Category Design","strategy","advanced","medium",
    "Use when designing new product categories, repositioning existing categories, or creating category-defining marketing strategies.",
    "You are a category strategist with expertise in category creation, positioning theory, and blue ocean strategy.",
    "## Category Design Workflow\n\n- [ ] 1. Category audit: Assess current category ({{current_category}}) for {{client_name}}\n- [ ] 2. Category design: Define new category boundaries and rules\n- [ ] 3. Value chain mapping: Map the category value chain and identify opportunities\n- [ ] 4. Buyer definition: Define the target category consumer\n- [ ] 5. Differentiation strategy: Create unique category positioning\n- [ ] 6. Launch strategy: Plan category launch and adoption",
    "## Category Design: {{client_name}}\n\n### Current Category: {{current_category}}\n### Proposed New Category: {{new_category_name}}\n\n### Category Design Rationale\n[Why does a new category make sense?]\n\n### New Category Definition\n| Attribute | Specification |\n|-----------|---------------|\n| Category name | |\n| Included products | |\n| Excluded products | |\n| Price range | |\n| Key attributes | |\n\n### Category Value Chain\n| Stage | Current State | Category Opportunity |\n|-------|--------------|---------------------|\n| | | |\n\n### Target Category Consumer\n| Attribute | Description |\n|-----------|-------------|\n| Demographics | |\n| Psychographics | |\n| Category behavior | |\n| Unmet need | |\n\n### Category Positioning\n**Tagline:** [Category tagline]\n**Key benefit claim:** [Main benefit]\n**Proof points:** [Why this is real]\n\n### Competitive Response Planning\n| Competitor | Likely Response | Counter-strategy |\n|------------|-----------------|------------------|\n| | | |\n\n### Launch Roadmap\n| Phase | Timeline | Actions |\n|-------|---------|---------|\n| Creation | | |\n| Education | | |\n| Expansion | | |",
    [{"name":"client_name","type":"string","required":True,"description":"Client name"},{"name":"current_category","type":"string","required":True,"description":"Current category"},{"name":"new_category_name","type":"string","required":True,"description":"Proposed new category name"},{"name":"industry","type":"string","required":True,"description":"Industry"},{"name":"target_consumer","type":"string","required":False,"description":"Target consumer description"}],
    [{"step":1,"name":"Category Audit","action":"Assess current category","verify":"Current dynamics understood"},{"step":2,"name":"Category Design","action":"Define new category","verify":"Category is ownable"},{"step":3,"name":"Value Chain Mapping","action":"Map value chain opportunities","verify":"Opportunities are real"},{"step":4,"name":"Buyer Definition","action":"Define target consumer","verify":"Consumer is specific"},{"step":5,"name":"Differentiation","action":"Create positioning","verify":"Positioning is ownable"},{"step":6,"name":"Launch Planning","action":"Plan category launch","verify":"Launch is achievable"}],
    ["New category is coherent and ownable","Value chain opportunity is real","Target consumer is specific","Positioning is ownable and defensible","Competitive response is anticipated","Launch roadmap is realistic"],
    ["presentation","document"],["maya","finn"],[],"category-design","strategy","blue-ocean",
    "Designs new product categories with definition, positioning, value chain mapping, and launch strategy.")

skills["change-control"] = make_skill("change-control","Change Control Process","operations","intermediate","low",
    "Use when managing change requests in projects, tracking scope changes, or implementing change control processes.",
    "You are a project manager specializing in change control, scope management, and project governance.",
    "## Change Control Workflow\n\n- [ ] 1. Change request submission: Capture change details ({{change_description}})\n- [ ] 2. Impact assessment: Evaluate impact on {{scope_elements}}\n- [ ] 3. Stakeholder review: Present change to {{decision_makers}}\n- [ ] 4. Approval tracking: Document decision and rationale\n- [ ] 5. Implementation planning: Plan how to implement approved change\n- [ ] 6. Change log maintenance: Update project documentation",
    "## Change Request: {{change_title}}\n\n### Request Details\n| Field | Value |\n|-------|-------|\n| Request ID | |\n| Submitted by | |\n| Date | |\n| Priority | |\n| Status | |\n\n### Change Description\n[Detailed description of requested change]\n\n### Impact Assessment\n| Element | Impact | Details |\n|---------|--------|---------|\n| Scope | | |\n| Schedule | | |\n| Budget | | |\n| Resources | | |\n| Quality | | |\n| Risk | | |\n\n### Alternatives Considered\n1. [Alternative approach 1]\n2. [Alternative approach 2]\n3. No change (status quo)\n\n### Decision\n| Decision Maker | Decision | Date |\n|----------------|----------|------|\n| | | |\n\n### Implementation Plan (if approved)\n| Step | Owner | Timeline |\n|------|-------|----------|\n| | | |",
    [{"name":"change_title","type":"string","required":True,"description":"Change request title"},{"name":"change_description","type":"string","required":True,"description":"Description of the change"},{"name":"scope_elements","type":"string","required":True,"description":"Project scope elements"},{"name":"decision_makers","type":"string","required":True,"description":"Decision makers"}],
    [{"step":1,"name":"Request Submission","action":"Capture change details","verify":"Change is clearly documented"},{"step":2,"name":"Impact Assessment","action":"Evaluate impacts","verify":"Impacts are quantified"},{"step":3,"name":"Stakeholder Review","action":"Present to decision makers","verify":"All stakeholders informed"},{"step":4,"name":"Approval Tracking","action":"Document decision","verify":"Decision is recorded"},{"step":5,"name":"Implementation","action":"Plan implementation","verify":"Plan is realistic"},{"step":6,"name":"Log Maintenance","action":"Update documentation","verify":"All docs updated"}],
    ["Change is clearly documented","Impacts are quantified","All alternatives considered","Decision is recorded with rationale","Implementation plan is realistic","Change log is updated"],
    ["spreadsheet","document"],["piper","sage"],[],"change-control","project-management","governance",
    "Manages change requests with impact assessment, approval tracking, and implementation planning.")

skills["channel-selection"] = make_skill("channel-selection","Channel Selection","media","intermediate","medium",
    "Use when selecting marketing channels for campaigns, evaluating channel effectiveness, or optimizing channel mix.",
    "You are a media strategist with expertise in channel strategy, media planning, and channel mix optimization.",
    "## Channel Selection Workflow\n\n- [ ] 1. Objective mapping: Match objectives ({{campaign_objectives}}) to channels\n- [ ] 2. Audience mapping: Match {{target_audience}} to channel reach\n- [ ] 3. Budget fitting: Assess channel cost vs {{total_budget}}\n- [ ] 4. Competitive review: See what channels competitors use\n- [ ] 5. Channel ranking: Score and rank channels\n- [ ] 6. Mix recommendation: Recommend optimal channel mix",
    "## Channel Selection: {{client_name}}\n\n### Campaign: {{campaign_name}}\n### Objective: {{campaign_objectives}}\n### Budget: {{total_budget}}\n\n### Target Audience\n{{target_audience}}\n\n### Channel Evaluation Matrix\n| Channel | Reach | Cost | Fit Score | Competitive | Final Score |\n|---------|-------|------|-----------|-------------|-------------|\n| | | | | | |\n\n### Recommended Channel Mix\n| Channel | Budget | % of Budget | Expected Reach |\n|---------|--------|-------------|----------------|\n| | | | |\n\n### Channel Rationale\n**Channel 1:** [Why this channel]\n**Channel 2:** [Why this channel]\n**Channel 3:** [Why this channel]\n\n### What We Are Not Recommending\n[Channels considered but not recommended, with reasons]\n\n### Implementation Priority\n| Phase | Channels | Timing |\n|-------|----------|--------|\n| Phase 1 | | |\n| Phase 2 | | |",
    [{"name":"client_name","type":"string","required":True,"description":"Client name"},{"name":"campaign_name","type":"string","required":True,"description":"Campaign name"},{"name":"campaign_objectives","type":"string","required":True,"description":"Campaign objectives"},{"name":"target_audience","type":"string","required":True,"description":"Target audience"},{"name":"total_budget","type":"string","required":True,"description":"Total budget"}],
    [{"step":1,"name":"Objective Mapping","action":"Match objectives to channels","verify":"All objectives addressed"},{"step":2,"name":"Audience Mapping","action":"Match audience to channels","verify":"Channels reach target"},{"step":3,"name":"Budget Fitting","action":"Assess channel costs","verify":"Costs are accurate"},{"step":4,"name":"Competitive Review","action":"Review competitor channels","verify":"Competitive landscape known"},{"step":5,"name":"Channel Ranking","action":"Score channels","verify":"Scoring is objective"},{"step":6,"name":"Mix Recommendation","action":"Recommend channel mix","verify":"Mix is optimal"}],
    ["All campaign objectives addressed","Channel recommendations reach target audience","Budget is realistic for selected channels","Competitive landscape considered","Mix is diverse and complementary","Recommendations are prioritized"],
    ["spreadsheet","analytics"],["nova","atlas"],["media-plan"],"channel-selection","media","strategy",
    "Evaluates and selects optimal marketing channels based on objectives, audience fit, budget, and competitive landscape.")

for skill_id, skill_data in skills.items():
    filepath = os.path.join(skills_dir, f"{skill_id}.json")
    with open(filepath, 'w') as f:
        json.dump(skill_data, f, indent=2)
    print(f"Written: {filepath}")

print(f"\nBatch 2 done: {len(skills)} skills")
